import esbuild from "esbuild";
import { spawn } from "child_process";
import process from "process";
import { builtinModules } from "node:module";
import { readFile } from "node:fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
// ESM→CJS shim for @anthropic-ai/claude-agent-sdk: the SDK calls
// createRequire(import.meta.url), but import.meta.url is undefined in a CJS
// bundle. Paired with \`define\` below, this maps it to the bundle's own URL.
const _importMetaUrl = require('url').pathToFileURL(__filename).href;
`;

const prod = process.argv[2] === "production";
const postcssArgs = ["node_modules/postcss-cli/index.js", "src/styles/index.css", "-o", "styles.css"];

function runCssBuild(watch = false) {
  return new Promise((resolve, reject) => {
    const args = watch ? [...postcssArgs, "--watch"] : postcssArgs;
    const child = spawn(process.execPath, args, {
      stdio: "inherit",
      shell: false,
    });

    child.once("error", reject);

    if (watch) {
      child.once("spawn", () => resolve(child));
      return;
    }

    child.once("exit", (code) => {
      if (code === 0) {
        resolve(child);
        return;
      }

      reject(new Error(`PostCSS exited with code ${code ?? "unknown"}.`));
    });
  });
}

/**
 * `@anthropic-ai/claude-agent-sdk` schedules its process-teardown timers with
 * `setTimeout(...).unref()`. Obsidian runs the plugin in Electron's renderer, where
 * `setTimeout` is the DOM one and returns a number, so `.unref` is undefined and
 * `ProcessTransport.close()` throws a TypeError out of an abort handler. The kill timer is
 * already scheduled by then, but the bookkeeping after it is skipped and the error surfaces
 * uncaught. Optional-call it, which is a no-op difference on a real Node timer.
 *
 * `@modelcontextprotocol/sdk` does the same in its stdio client transport, so it gets the
 * same treatment. The check afterwards reads the emitted bundle rather than counting
 * patches, so a dependency that moves the call, or a new one that introduces its own,
 * fails the build instead of shipping a renderer crash.
 */
const nodeTimerUnrefShim = {
  name: "node-timer-unref-shim",
  setup(build) {
    const vendored =
      /(@anthropic-ai[\\/]claude-agent-sdk|@modelcontextprotocol[\\/]sdk)[\\/].*\.(js|mjs|cjs)$/;
    build.onLoad({ filter: vendored }, async (args) => {
      const source = await readFile(args.path, "utf8");
      if (!source.includes(".unref()")) return null;
      return { contents: source.replaceAll(".unref()", ".unref?.()") };
    });
    build.onEnd(async (result) => {
      if (result.errors.length > 0) return;
      const outfile = build.initialOptions.outfile;
      const bundle = await readFile(outfile, "utf8");
      if (bundle.includes(".unref()")) {
        throw new Error(
          `${outfile} still contains a bare .unref() call, which throws in Electron's ` +
            "renderer. Widen node-timer-unref-shim's filter to cover its package.",
        );
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  plugins: [nodeTimerUnrefShim],
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    // The Agent SDK imports node builtins via the `node:` protocol (e.g.
    // `node:module`, `node:fs`). `builtinModules` lists bare names only, so
    // externalize the prefixed variants too, Obsidian runs in Electron with
    // Node integration, so these resolve at runtime like the bare builtins.
    ...builtinModules.map((m) => `node:${m}`),
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  // See the `_importMetaUrl` shim in the banner above.
  define: { "import.meta.url": "_importMetaUrl" },
  outfile: "main.js",
});

if (prod) {
  await runCssBuild();
  await context.rebuild();
  await context.dispose();
  process.exit(0);
} else {
  const cssWatcher = await runCssBuild(true);
  const cleanup = async () => {
    cssWatcher.kill();
    await context.dispose();
    process.exit(0);
  };

  process.once("SIGINT", () => {
    void cleanup();
  });
  process.once("SIGTERM", () => {
    void cleanup();
  });

  await context.watch();
}
