import esbuild from "esbuild";
import { spawn } from "child_process";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
// ESM→CJS shim for @anthropic-ai/claude-agent-sdk: the SDK calls
// createRequire(import.meta.url), but import.meta.url is undefined in a CJS
// bundle. Paired with \`define\` below, this maps it to the bundle's own URL.
const _importMetaUrl = require('url').pathToFileURL(__filename).href;
`;

const mode = process.argv[2] ?? "watch";
const prod = mode === "production";
// `driver` is the development bundle built once instead of watched: the live scenario driver
// installs a build into a scratch vault per run, and a watcher never exits.
const oneShot = prod || mode === "driver";
const postcssArgs = ["node_modules/postcss-cli/index.js", "src/styles/index.css", "-o", "styles.css"];

function runCssBuild(watch = false) {
  return new Promise((resolve, reject) => {
    const args = watch ? [...postcssArgs, "--watch"] : postcssArgs;
    const child = spawn(process.execPath, args, {
      stdio: "inherit",
      shell: false,
    });

    child.once("error", reject);

    if (watch) {
      child.once("spawn", () => resolve(child));
      return;
    }

    child.once("exit", (code) => {
      if (code === 0) {
        resolve(child);
        return;
      }

      reject(new Error(`PostCSS exited with code ${code ?? "unknown"}.`));
    });
  });
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    // The Agent SDK imports node builtins via the `node:` protocol (e.g.
    // `node:module`, `node:fs`). `builtinModules` lists bare names only, so
    // externalize the prefixed variants too, Obsidian runs in Electron with
    // Node integration, so these resolve at runtime like the bare builtins.
    ...builtinModules.map((m) => `node:${m}`),
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  define: {
    // See the `_importMetaUrl` shim in the banner above.
    "import.meta.url": "_importMetaUrl",
    // The live scenario driver's bridge and scripted provider are compiled out of a release
    // artifact entirely: a literal `false` makes every guarded call site dead code, and
    // tree-shaking then drops the modules behind them (RFC-0013).
    DEV_DRIVER: prod ? "false" : "true",
  },
  outfile: "main.js",
});

if (oneShot) {
  await runCssBuild();
  await context.rebuild();
  await context.dispose();
  process.exit(0);
} else {
  const cssWatcher = await runCssBuild(true);
  const cleanup = async () => {
    cssWatcher.kill();
    await context.dispose();
    process.exit(0);
  };

  process.once("SIGINT", () => {
    void cleanup();
  });
  process.once("SIGTERM", () => {
    void cleanup();
  });

  await context.watch();
}
